name = "LocalPolynomialDensityEstimation"
uuid = "83fb4684-3fee-4d04-98f8-7882db2935bc"
authors = ["Pierre Navaro <pierre.navaro@math.cnrs.fr> and contributors"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TypedPolynomials = "afbbf031-7a57-5f58-a1b9-b774a0fad08d"

[compat]
Aqua = "0.8"
DocStringExtensions = "0.9"
MultivariatePolynomials = "0.5"
RecipesBase = "1.3"
Statistics = "1"
Test = "1"
TypedPolynomials = "0.4"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
